cache:
  apt: true

language: php

## Cache composer downloads.
cache:
  directories:
    # Cache directory for older Composer versions.
    - $HOME/.composer/cache/files
    # Cache directory for more recent Composer versions.
    - $HOME/.cache/composer/files

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm

matrix:
  include:
    - php: 5.3
      dist: precise
  allow_failures:
    - php: hhvm
    - php: nightly
    - php: 5.3

before_install:
  ## Packages
  - sudo apt-get -qq update

before_script:
  ## Composer
  - composer self-update
  - composer install --prefer-dist
  ## PHPDocumentor
  ## - mkdir -p build/docs
  ## - mkdir -p build/coverage

script:
  # Search for PHP syntax errors.
  - find -L . -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
  ## PHP_CodeSniffer
  - ./vendor/bin/phpcs ./classes/src/ --standard=PSR2 -n
  ## PHP Copy/Paste Detector
  # - ./vendor/bin/phpcpd ./classes/src/
  ## PHP Mess Detector
  - ./vendor/bin/phpmd ./classes/src/ text ./phpmd.xml.dist
  ## PHPUnit
  - ./vendor/bin/phpunit -c ./unitTests/ --coverage-text --coverage-html ./build/coverage
  ## PHPLOC
  - ./vendor/bin/phploc ./classes/src/
  ## PHPDocumentor
  ## - ./vendor/bin/phpdoc -q -d ./classes/src -t ./build/docs --template="responsive-twig"

notifications:
  email: false
